//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public int LogId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string Action { get; set; }
        public string Details { get; set; }
        public string IPAddress { get; set; }
    
        public virtual User User { get; set; }
    }
}
