//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockedIP
    {
        public int BlockId { get; set; }
        public string IPAddress { get; set; }
        public string Reason { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
        public int BlockedByUserId { get; set; }
        public Nullable<System.DateTime> ExpiryDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
    }
}
