//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginAttempt
    {
        public int AttemptId { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
        public bool IsSuccessful { get; set; }
        public string IPAddress { get; set; }
        public string UserAgent { get; set; }
    }
}
