//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PasswordManagerEntities : DbContext
    {
        public PasswordManagerEntities()
            : base("name=PasswordManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AuditLog> AuditLogs { get; set; }
        public virtual DbSet<LoginAttempt> LoginAttempts { get; set; }
        public virtual DbSet<PasswordGroup> PasswordGroups { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StoredPassword> StoredPasswords { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<BlockedIP> BlockedIPs { get; set; }
        public virtual DbSet<PasswordPolicy> PasswordPolicies { get; set; }
        public virtual DbSet<SecurityAlert> SecurityAlerts { get; set; }
    }
}
