//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityAlert
    {
        public int AlertId { get; set; }
        public string AlertType { get; set; }
        public string Severity { get; set; }
        public string Description { get; set; }
        public string Source { get; set; }
        public string IPAddress { get; set; }
        public string Username { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsResolved { get; set; }
        public Nullable<int> ResolvedByUserId { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string Notes { get; set; }
    
        public virtual User User { get; set; }
    }
}
