//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoredPassword
    {
        public int PasswordId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string SiteName { get; set; }
        public string SiteUrl { get; set; }
        public string Username { get; set; }
        public string EncryptedPassword { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
    
        public virtual PasswordGroup PasswordGroup { get; set; }
        public virtual User User { get; set; }
    }
}
